# Generated by Django 4.0.2 on 2022-03-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_mens_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Kids',
        ),
        migrations.DeleteModel(
            name='Womens',
        ),
    ]
