# Generated by Django 4.0.2 on 2022-04-07 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='detailsqr',
            fields=[
                ('qr_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('TransactionID', models.IntegerField()),
                ('UPINumber', models.IntegerField()),
                ('UPIIDHAi', models.CharField(default='none', max_length=50)),
                ('File', models.ImageField(default='https://via.placeholder.com/500x500.png?text=Default', upload_to='QRSuccess')),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
