# Generated by Django 4.0.2 on 2022-04-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_detailsqr_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsqr',
            name='File',
            field=models.ImageField(default='', upload_to='Home\\mensimg\\images'),
        ),
    ]
