# Generated by Django 4.0.2 on 2022-04-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_detailsqr_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailsqr',
            old_name='File',
            new_name='Filehai',
        ),
    ]
