# Generated by Django 4.0.2 on 2022-04-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_detailsqr_filehai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsqr',
            name='Filehai',
            field=models.ImageField(default='', upload_to='media\\Home\\qrsuccess\\images'),
        ),
    ]
